/**
 * 10 Curated Companies with Diverse JDs for the PM Internship Scheme
 */
export const COMPANIES_CATALOG = [
  {
    id: 'avolve',
    company_name: 'AVOLVE Technologies Pvt. Ltd.',
    sector: 'IT / Technology',
    role: 'Software & Data Engineering Intern',
    location: 'Hyderabad',
    state: 'Telangana',
    vacancies: 20,
    target_skills: ['python', 'sql', 'machine-learning', 'javascript', 'problem-solving'],
    min_cgpa: 7.0,
    max_backlogs: 0,
    eligible_qualifications: ['B.Tech', 'MCA', 'BSc'],
    stipend: '₹5,000 / month',
    duration: '12 Months',
    quotas: { General: 50, OBC: 25, SC: 15, ST: 5, EWS: 5 },
    description: 'Work on enterprise data pipelines, backend APIs in Python, SQL optimization, and predictive AI model deployments.'
  },
  {
    id: 'tcs',
    company_name: 'Tata Consultancy Services (TCS)',
    sector: 'Cloud & Enterprise IT',
    role: 'Cloud Systems & DevOps Intern',
    location: 'Bengaluru',
    state: 'Karnataka',
    vacancies: 25,
    target_skills: ['python', 'java', 'javascript', 'sql', 'critical-thinking'],
    min_cgpa: 6.5,
    max_backlogs: 0,
    eligible_qualifications: ['B.Tech', 'MCA', 'BSc', 'BCA'],
    stipend: '₹5,000 / month',
    duration: '12 Months',
    quotas: { General: 50, OBC: 27, SC: 15, ST: 5, EWS: 3 },
    description: 'Assist in cloud infrastructure monitoring, microservices CI/CD pipeline automation, and enterprise system migrations.'
  },
  {
    id: 'bel',
    company_name: 'Bharat Electronics Ltd (BEL)',
    sector: 'Defence & Electronics',
    role: 'Embedded Systems & IoT Intern',
    location: 'Pune',
    state: 'Maharashtra',
    vacancies: 15,
    target_skills: ['electrical', 'mechanical', 'c++', 'cad', 'problem-solving'],
    min_cgpa: 7.0,
    max_backlogs: 0,
    eligible_qualifications: ['B.Tech', 'Diploma'],
    stipend: '₹5,000 / month',
    duration: '12 Months',
    quotas: { General: 50, OBC: 27, SC: 15, ST: 5, EWS: 3 },
    description: 'Hands-on embedded C/C++ firmware development, microcontroller interfacing, hardware testing, and radar telemetry analysis.'
  },
  {
    id: 'hdfc',
    company_name: 'HDFC Bank',
    sector: 'Banking & Fintech',
    role: 'Financial Analyst & Risk Intern',
    location: 'Mumbai',
    state: 'Maharashtra',
    vacancies: 20,
    target_skills: ['finance', 'accounting', 'excel', 'sql', 'data-analysis'],
    min_cgpa: 6.8,
    max_backlogs: 0,
    eligible_qualifications: ['B.Com', 'BBA', 'MBA', 'BA'],
    stipend: '₹5,000 / month',
    duration: '10 Months',
    quotas: { General: 50, OBC: 25, SC: 15, ST: 5, EWS: 5 },
    description: 'Perform credit risk assessments, portfolio trend reporting with advanced Excel & SQL, and retail banking fraud detection modeling.'
  },
  {
    id: 'tatamotors',
    company_name: 'Tata Motors',
    sector: 'Automotive & EV',
    role: 'EV Powertrain & Mechanical Intern',
    location: 'Pune',
    state: 'Maharashtra',
    vacancies: 15,
    target_skills: ['mechanical', 'cad', 'electrical', 'problem-solving', 'teamwork'],
    min_cgpa: 6.5,
    max_backlogs: 1,
    eligible_qualifications: ['B.Tech', 'Diploma'],
    stipend: '₹5,000 / month',
    duration: '12 Months',
    quotas: { General: 50, OBC: 25, SC: 15, ST: 5, EWS: 5 },
    description: 'Work with the electric vehicle R&D team on battery pack mechanical thermal design, CAD drafting, and vehicle assembly QA.'
  },
  {
    id: 'apollo',
    company_name: 'Apollo Hospitals Group',
    sector: 'Healthcare & HealthTech',
    role: 'Healthcare Informatics Intern',
    location: 'Chennai',
    state: 'Tamil Nadu',
    vacancies: 10,
    target_skills: ['healthcare', 'data-analysis', 'research', 'excel', 'communication'],
    min_cgpa: 6.5,
    max_backlogs: 0,
    eligible_qualifications: ['BSc', 'B.Pharm', 'BA', 'B.Tech'],
    stipend: '₹5,000 / month',
    duration: '12 Months',
    quotas: { General: 50, OBC: 25, SC: 15, ST: 5, EWS: 5 },
    description: 'Analyze electronic health record (EHR) systems, clinical data tracking, patient outcome statistics, and telemedicine operations.'
  },
  {
    id: 'lt',
    company_name: 'Larsen & Toubro (L&T)',
    sector: 'Infrastructure & Engineering',
    role: 'Civil Infrastructure & BIM Intern',
    location: 'Delhi',
    state: 'Delhi NCR',
    vacancies: 15,
    target_skills: ['civil', 'cad', 'project-management', 'critical-thinking', 'teamwork'],
    min_cgpa: 6.5,
    max_backlogs: 1,
    eligible_qualifications: ['B.Tech', 'Diploma'],
    stipend: '₹5,000 / month',
    duration: '12 Months',
    quotas: { General: 50, OBC: 25, SC: 15, ST: 5, EWS: 5 },
    description: 'Participate in Building Information Modeling (BIM), structural drafting review, metro rail civil inspection, and project cost tracking.'
  },
  {
    id: 'itc',
    company_name: 'ITC Limited',
    sector: 'Agriculture & AgriTech',
    role: 'Agri-Supply Chain & Tech Intern',
    location: 'Kolkata',
    state: 'West Bengal',
    vacancies: 12,
    target_skills: ['agriculture', 'supply-chain', 'data-analysis', 'communication'],
    min_cgpa: 6.0,
    max_backlogs: 0,
    eligible_qualifications: ['BSc', 'B.Com', 'BA', 'BBA'],
    stipend: '₹5,000 / month',
    duration: '11 Months',
    quotas: { General: 50, OBC: 27, SC: 15, ST: 5, EWS: 3 },
    description: 'Engage with ITC e-Choupal networks, crop yield forecasting data collection, farm-to-factory logistics, and rural market distribution.'
  },
  {
    id: 'reliance',
    company_name: 'Reliance New Energy',
    sector: 'Clean Energy & Power',
    role: 'Renewable Energy Systems Intern',
    location: 'Ahmedabad',
    state: 'Gujarat',
    vacancies: 15,
    target_skills: ['electrical', 'mechanical', 'research', 'critical-thinking', 'cad'],
    min_cgpa: 7.0,
    max_backlogs: 0,
    eligible_qualifications: ['B.Tech', 'BSc', 'Diploma'],
    stipend: '₹5,000 / month',
    duration: '12 Months',
    quotas: { General: 50, OBC: 25, SC: 15, ST: 5, EWS: 5 },
    description: 'Analyze solar PV panel efficiency datasets, green hydrogen storage research, and energy transmission grid monitoring.'
  },
  {
    id: 'zomato',
    company_name: 'Zomato Limited',
    sector: 'Consumer Tech',
    role: 'Growth & Product Marketing Intern',
    location: 'Gurugram',
    state: 'Haryana',
    vacancies: 18,
    target_skills: ['marketing', 'digital-marketing', 'content-writing', 'communication', 'data-analysis'],
    min_cgpa: 6.5,
    max_backlogs: 1,
    eligible_qualifications: ['BA', 'BBA', 'B.Com', 'BSc'],
    stipend: '₹5,000 / month',
    duration: '10 Months',
    quotas: { General: 50, OBC: 25, SC: 15, ST: 5, EWS: 5 },
    description: 'Design growth marketing campaigns, analyze customer retention cohorts with data analytics, write creative copy, and audit merchant listings.'
  }
];
